version: "3"

services:
  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - 8000:80
      volumes:
        - ./frontend/dist/:/var/www/dist/
        - ./nginx/:/etc/nginx/
      depends_on:
        - frontend
        - backend
  frontend:
    container_name: "moviefun-frontend"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
  backend:
    restart: always
    container_name: "moviefun-backend"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_DEBUG=1