version: "3"

services:
  nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - 8000:80
      volumes:
        - ./client/build:/var/www
        - ./nginx/:/etc/nginx/conf.d/
      depends_on:
        - frontend
        - backend
  frontend:
    container_name: "moviefun-client"
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app/client
  backend:
    restart: always
    container_name: "moviefun-backend"
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    volumes:
      - .:/app
    environment:
      - FLASK_DEBUG=1